import { Section, SkeletonLines } from './Section';
import { Icon } from '@/components/ds/Icon';

type DescriptionData = { blurb?: string; error?: string } | undefined;

export function DescriptionCard({ data }: { data?: DescriptionData }) {
  const state = !data ? 'skeleton' : data.error ? (data.blurb ? 'partial' : 'error') : 'complete';
  return (
    <Section
      num="01"
      title="What is this domain?"
      state={state}
      errorText={data?.error}
      anchor="sec-description"
      skeleton={
        <div
          className="surface"
          style={{
            padding: 24,
            borderLeft: '2px solid var(--bg-3)',
            display: 'flex',
            flexDirection: 'column',
            gap: 10,
          }}
        >
          <SkeletonLines lines={3} />
          <div
            style={{
              marginTop: 14,
              paddingTop: 14,
              borderTop: '1px dashed var(--border)',
              display: 'flex',
              alignItems: 'center',
              gap: 8,
              fontSize: 11.5,
              color: 'var(--fg-4)',
            }}
          >
            <span className="status status-running">
              <span className="pulse" /> generating
            </span>
            <span className="mono" style={{ letterSpacing: '0.04em' }}>
              Gemini is reading your site…
            </span>
          </div>
        </div>
      }
    >
      <blockquote
        style={{
          margin: 0,
          padding: '24px 28px',
          background: 'var(--bg-1)',
          borderLeft: '2px solid var(--signal)',
          borderRadius: '0 8px 8px 0',
          fontSize: 18,
          lineHeight: 1.6,
          color: 'var(--fg)',
          letterSpacing: '-0.01em',
          fontWeight: 400,
        }}
      >
        {data?.blurb}
        <div
          style={{
            marginTop: 16,
            paddingTop: 14,
            borderTop: '1px dashed var(--border)',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            fontSize: 11.5,
            color: 'var(--fg-4)',
            flexWrap: 'wrap',
            gap: 6,
          }}
        >
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
            <Icon.spark style={{ color: 'var(--signal)' }} />
            <span className="mono" style={{ letterSpacing: '0.05em', textTransform: 'uppercase' }}>
              Generated by Gemini 2.5
            </span>
          </span>
        </div>
      </blockquote>
    </Section>
  );
}
